name: Replace Bear Link with Markdown Link
on:
  push:
  workflow_dispatch:

jobs:
  run_python_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
    
      - name: Run Push Python Script
        run: python .github/workflows/python/push.py
        working-directory: ${{ github.workspace }}/..

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5

