# on: [push]

# jobs:
#   find-and-replace-job:
#     runs-on: ubuntu-latest
#     name: 'Find and replace master glossary'
#     steps:
#       # Replace all the occurrences of 'hello' with 'world' in all the txt files, 
#       # excluding the node_modules folder
#       - name: Replace Master Glossary
#         uses: richardrigutins/replace-in-files@v2
#         with:
#           files: "${{env.GITHUB_REPOSITORY}}/**/*.md"
#           search-text: "[[Master Glossary]]"
#           replacement-text: "[Master Glossary](Main/Master Glossary.md)"
#           encoding: 'utf8'
#           max-parallelism: 10

#       - name: Replace Table of Contents
#         uses: richardrigutins/replace-in-files@v2
#         with:
#           files: "${{env.GITHUB_REPOSITORY}}/**/*.md"
#           search-text: "[[Return to Table of Contents]]"
#           replacement-text: "[Return to Table of Contents](README.md)"
#           encoding: 'utf8'
#           max-parallelism: 10




name: Convert Bear Link to Markdown Link Workflow
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - name: Find and Replace - Return to Master Glossary
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: '[[Return to Master Glossary]]'
          replace: '[Return to Master Glossary](Main/Master&#32;Glossary.md)'
          regex: false
          exclude: '*.yml'
      - name: Find and Replace - Return to Table of Contents
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: '[[Return to Table of Contents]]'
          replace: '[Return to Table of Contents](README.md)'
          regex: false
          exclude: '*.yml'
#      - name: Find and Replace - Regex
        #uses: jacobtomlinson/gha-find-replace@v3
        #with:
          #find: '(?<=[[)(.*)(?=]])'
          #replace: '[Return to Master Glossary](Main/Master&#32;Glossary.md)'
          #regex: true
          #exclude: '*.yml'

#      - name: Push changes
        #uses: stefanzweifel/git-auto-commit-action@v4



name: Convert Markdown Link to Bear Link Workflow
on: [pull]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - name: Find and Replace - Return to Master Glossary
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: '[Return to Master Glossary](Main/Master&#32;Glossary.md)'
          replace: '[[Return to Master Glossary]]'
          regex: false
          exclude: '*.yml'
      - name: Find and Replace - Return to Table of Contents
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: '[Return to Table of Contents](README.md)'
          replace: '[[Return to Table of Contents]]'
          regex: false
          exclude: '*.yml'

    